defaults:
  - /base_configs/dataModule_config.yaml@_here_ 
  - _self_
# make sure _self_ is in the end as it means to inherent last from this file meaning overwriting the inhereted values if needed

global_batch_size: 32
# add more as required
dataModuleType : Real # can  be Mock or Real as of now.
msc_config : "/home/shadeform/coom/configs/experiment_0/msc_config_aistore.yaml"
data_paths : ["msc://my_test_data/my-gpt_text_document"]
object_storage_cache_path : "/home/shadeform/oject_storage_cache"
streaming : True # has to True or False