config_path_prefix: /

base_model: EKAModel

base_model_config: EKAConfig
base_model_configuration_path: base_model_config.yaml

data_model : EKAPreTrainingDataModule
data_loader_config_path: data_loader_config.yaml
optimizer_config_path: optimizer_config.yaml
trainer_config_path: trainer_config.yaml
logger_config_path: logger_config.yaml
profiler_config_path : profiler_config.yaml
callback_config_path : callback_config.yaml